<a href="https://colab.research.google.com/github/abhishekshah5486/classic-machine-learning/blob/main/ridge_regression_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_diabetes

In [3]:
X, y = load_diabetes(return_X_y=True)

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=2)

In [6]:
from sklearn.linear_model import SGDRegressor

In [7]:
lr = SGDRegressor(penalty='l2', max_iter = 500, eta0=0.1, learning_rate='constant', alpha=0.001)

In [8]:
lr.fit(X_train, y_train)

SGDRegressor(alpha=0.001, eta0=0.1, learning_rate='constant', max_iter=500)

In [9]:
lr.coef_

array([  29.1993416 , -113.35674904,  394.73733318,  264.76933952,
         -9.63118319,  -67.96298143, -169.42217315,  106.17545281,
        364.91286123,   96.46264936])

In [10]:
lr.intercept_

array([147.98476589])

### Code from Scratch: Ridge Regression - Gradient Descent

In [21]:
class RidgeRegression():
  def __init__(self, alpha=0.1, learning_rate=0.01, max_iter=100):
    self.alpha = alpha
    self.learning_rate = learning_rate
    self.max_iter = max_iter
    self.coef_ = None
    self.intercept_ = None
    self.dW = None
    self.db = None

In [43]:
def fit(self, X, y):
  self.coef_ = np.ones(X.shape[1])
  self.intercept_ = 0
  theta = np.insert(self.coef_, 0, self.intercept_)
  X = np.insert(X, 0, 1, axis=1)

  for i in range(self.max_iter):
    theta_der = X.T.dot(X).dot(theta) - X.T.dot(y) + self.alpha * theta
    theta = theta - self.learning_rate * theta_der

  self.coef_ = theta[1:,]
  self.dW = self.coef_
  self.intercept_ = theta[0]
  self.db = self.intercept_
  return self

RidgeRegression.fit = fit

In [44]:
def predict(self, X):
  return np.dot(X, self.dW) + self.db

RidgeRegression.predict = predict

In [45]:
rr = RidgeRegression(alpha = 0.001, learning_rate=0.005, max_iter=500)

In [46]:
rr.fit(X_train, y_train)

In [47]:
rr.coef_

array([  19.50919039, -162.92602513,  478.95477998,  317.86376108,
        -34.07709121, -108.63608801, -193.66871805,  106.94769192,
        437.10746813,  103.57606041])

In [48]:
rr.intercept_

152.03121813717044